version: "3.9"
services:
  redis-master:
    image: redis:latest
    container_name: ms-redis-master
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
      - ./master/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis-slave1:
    image: redis:latest
    container_name: ms-redis-slave1
    depends_on:
      - redis-master
    ports:
      - "6380:6379"
    volumes:
      - redis-slave1-data:/data
      - ./slave1/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis-slave2:
    image: redis:latest
    container_name: ms-redis-slave2
    depends_on:
      - redis-master
    ports:
      - "6381:6379"
    volumes:
      - redis-slave2-data:/data
      - ./slave2/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  redis-master-data:
  redis-slave1-data:
  redis-slave2-data:
