server:
  port: 8081

spring:
  cache:
    time-to-live: 3600 #缓存过期时间
    cache-enable: false  #是否启用缓存
    #redis-shiro: true  #是否启用redis缓存shiro， cache-enable为true的时候起作用
    #     如果开启缓存@EnableCaching 默认的缓存是springboot的SimpleCache
    #     如果引入redis等缓存后，就会用引入的缓存框架，如果不想用可以强制type:simple
    #    type: simple
  redis:
    host: 192.168.137.141  #redis服务器地址
    port: 6379           #redis服务器端口号
    password: 123456     #redis密码
    timeout: 30000       #连接超时时间
    database: 0         #Redis数据库索引（默认为0）
